const movieList = [
  {
    imageUrl: "/poster.jpeg",
    title: "John Wick",
    rating: 4.7,
    type: "movies",
    casts: ["ken Aremoh", "kenmoh Godwin", "Asunumhe Ejike"],
    poster: "/movieposter.jpg",
    year: 2020,
    summary: "lorem",
  },
  {
    imageUrl: "/poster1.jpeg",
    title: "JI Joe",
    rating: 3.7,
    type: "movies",
    casts: ["ken Aremoh", "kenmoh Godwin", "Asunumhe Ejike"],
    poster: "/movieposter.jpg",
    year: 2023,
    summary: "lorem",
  },
  {
    imageUrl: "/poster2.jpeg",
    title: "Maleficient",
    rating: 4.3,
    type: "movies",
    casts: ["ken Aremoh", "kenmoh Godwin", "Asunumhe Ejike"],
    poster: "/movieposter.jpg",
    year: 2021,
    summary: "lorem",
  },
  {
    imageUrl: "/poster1.jpeg",
    title: "Liverpool",
    rating: 4.7,
    type: "movies",
    casts: ["ken Aremoh", "kenmoh Godwin", "Asunumhe Ejike"],
    poster: "/movieposter.jpg",
    year: 2023,
    summary: "lorem",
  },
  {
    imageUrl: "/poster.jpeg",
    title: "Arsenal",
    rating: 4.7,
    type: "movies",
    casts: ["ken Aremoh", "kenmoh Godwin", "Asunumhe Ejike"],
    poster: "/movieposter.jpg",
    year: 2021,
    summary: "lorem",
  },
  {
    imageUrl: "/poster2.jpeg",
    title: "Chelsea",
    rating: 4.7,
    type: "movies",
    casts: ["ken Aremoh", "kenmoh Godwin", "Asunumhe Ejike"],
    poster: "/movieposter.jpg",
    year: 2020,
    summary: "lorem",
  },
  {
    imageUrl: "/poster1.jpeg",
    title: "Real Madrid",
    rating: 4.7,
    type: "movies",
    casts: ["ken Aremoh", "kenmoh Godwin", "Asunumhe Ejike"],
    poster: "/movieposter.jpg",
    year: 2021,
    summary: "lorem",
  },
  {
    imageUrl: "/poster.jpeg",
    title: "Newcastsle",
    rating: 4.7,
    type: "movies",
    casts: ["ken Aremoh", "kenmoh Godwin", "Asunumhe Ejike"],
    poster: "/movieposter.jpg",
    year: 2022,
    summary: "lorem",
  },
];

export default movieList;
